added uncache action

diff --git a/bin/pyverman b/bin/pyverman
--- a/bin/pyverman
+++ b/bin/pyverman
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 OPTIMIZATIONS=false
-VERSION="0.0.1"
+VERSION="0.5.0"
 DEPENDENCIES="build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev curl libbz2-dev liblzma-dev lzma tk tk-dev libsqlite3-dev"
 
 while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
@@ -12,13 +12,14 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
     echo "usage: pyverman [options] action version"
     echo "flags:"
     echo "   --help -h                  displays this message"
-    echo "   --enable-optimizations -O  configures python with optimizations (only affects \"install\" command)"
+    echo "   --enable-optimizations -O  configures python with optimizations (only affects install and cache commands)"
     echo "   --version                  lists script version"
     echo "   --verbose -v               doesn't route make info to /dev/null"
     echo "   --list-dependencies -d     lists dependencies for building python"
     echo "actions:"
     echo "     install                  installs selected version from the internet"
     echo "     uninstall                removes selected version from system"
+    echo "     cache                    downloads and configures selected version to cache"
     echo "     uncache                  removes selected version's build files from cache"
     echo "     reinstall                reinstalls python from build files"
     exit
@@ -128,11 +129,63 @@ case $1 in
       echo "error: invalid version"
       exit 1
     fi
-    echo "Removing Version $VERSION"
+    echo -n "Removing Version $VERSION..."
     sudo rm -rf /usr/bin/python$VERSION &> /dev/null
     sudo rm -rf /usr/lib/python$VERSION &> /dev/null
     sudo rm -rf /usr/local/bin/python$VERSION &> /dev/null
     sudo rm -rf /usr/local/lib/python$VERSION $> /dev/null
+    echo "DONE"
+    exit 0
+    ;;
+  cache)
+    if [[ -z $VERSION ]]; then
+      echo "error: please specify a version to cache" >&2
+      exit 1
+    fi
+    echo -n "Downloading Version ${VERSION} to cache"
+    if [[ $OPTIMIZATIONS == true ]]; then
+      echo -n " with optimizations"
+    fi
+    echo ""
+    echo "entering directory $HOME/.pyverman"
+    if [[ ! -d "$HOME/.pyverman" ]]; then
+      mkdir $HOME/.pyverman
+    fi
+    cd $HOME/.pyverman
+    echo "creating version directory"
+    if [[ ! -d $VERSION ]]; then
+      mkdir $VERSION
+    fi
+    cd $VERSION
+    echo "downloading version tarball"
+    if curl --head --silent --fail https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tgz &> /dev/null; then
+      curl -o $VERSION.tgz https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tgz
+    else
+     echo "error: version does not exist! (did you spell it correctly?)"
+     exit 1
+    fi
+    echo -n "unpacking tarball..."
+    tar -xzf $VERSION.tgz
+    echo "DONE"
+    echo "entering unpacked directory"
+    cd Python-$VERSION
+    echo -n "Configuring python..."
+    if [[ $VERBOSE == true ]]; then
+      if [[ $OPTIMIZATIONS == true ]]; then
+        ./configure --enable-optimizations
+      else
+        ./configure
+      fi
+    else
+      if [[ $OPTIMIZATIONS == true ]]; then
+        ./configure --enable-optimizations > /dev/null
+      else
+        ./configure &> /dev/null
+      fi
+    fi
+    echo "DONE"
+    echo "Python $VERSION saved to cache"
+    exit 0
     ;;
   uncache)
     if [[ -z $VERSION ]]; then
@@ -140,7 +193,13 @@ case $1 in
       exit 1
     fi
     echo "Removing Version ${VERSION} from cache"
-    
+    if [[ -d $HOME/.pyverman/$VERSION ]]; then
+      rm -rf $HOME/.pyverman/$VERSION
+    else
+      echo "error: version not in cache" >&2
+      exit 1
+    fi
+    exit 0
     ;;
   reinstall)
     if [[ -z $VERSION ]]; then
@@ -148,5 +207,30 @@ case $1 in
       exit 1
     fi
     echo "Reinsatlling Version ${VERSION} from cache"
+    echo "Entering version directory"
+    if [[ ! -d "$HOME/.pyverman/$VERSION" ]]; then
+      echo "error: version not in cache" >&2
+    fi
+    cd $HOME/.pyverman/$VERSION/Python-$VERSION
+
+    echo "building python may take some time if optimizations are enabled"
+    echo "if this step takes longer than a few hours, an error has probably occured"
+    echo -n "building python..."
+    if [[ $VERBOSE == true ]]; then
+      make
+    else
+      make &> /dev/null
+    fi
+    echo "DONE"
+    echo -n "installing python..."
+    if [[ $VERBOSE == true ]]; then
+      sudo make altinstall
+    else
+      sudo make altinstall > /dev/null
+    fi
+    echo "DONE"
+    
+    echo "Installation complete! use python$VERSIONSHORT to use python and pip$VERSIONSHORT to install modules"
+    exit 0
     ;;
 esac;
